FFM-7412 - Bump ff-eventsource dependency to fix socket leak
harness/ff-nodejs-server-sdk pull request #69
Opened 2023-04-13 17:24 UTC by andybharness

FFM-7412 - Bump ff-eventsource dependency to fix socket leak

What
This updates the Harness fork of the eventsource lib to use an updated bug fixed version: If we're already retrying a stream endpoint, avoid scheduling another retry. Instead let the existing retry run its course.

Why
We're seeing the SDK endlessly spin with retries when a stream endpoint drops.

Testing
Tested manually with a custom proxy to drop the stream endpoint and reproduce the spin

2023-04-15 00:42 UTC, bmjen approved these changes

2023-04-15 00:43 UTC, bmjen commented
Approved, but need to release eventsource and rerun tests before this one can go through.

2023-04-15 18:29 UTC, erdirowlands requested changes
The ff-eventsource version that this PR bumps cause the library not to do any retries. We can't merge this until that is sorted.

Sticking in "Request changes" for now.

2023-06-26 11:43 UTC, erdirowlands commented
Closing as @andybharness has implemented SSE without using an external library in 

https://github.com/harness/ff-nodejs-server-sdk/pull/70

2023-06-26 11:43 UTC, closed without merging